id: P005566
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS19195
  title: མན་ངག་རིན་ཆེན་གསེར་སྒྲོམ།
  author: ''
  volumes:
    59a9db9f3d354d20b9936d97f2e6b384:
      image_group_id: I8LS19197
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
